### ISSUE TITLE
$coverageReport = new RetailerFeedbackReport class not found

### ISSUE THREAD

**Issue by Alias1975** [jecksolovyev/brandbank-soap-api-client#3]
Hi, 
there's someone that can help me.
i try this code:

```
<?php
require_once __DIR__ . '/autoload.php';

// initiate the API
$api = new BrandbankSOAPAPIClient\BrandbankSOAPAPIClient(
    new BrandbankSOAPAPIClient\Authenticator\HeaderGuidAuthenticator('my-brandbank-id')
);


$items = ['8001100066998'];
$coverageReport = new RetailerFeedbackReport(new Message(new DateTime()));
foreach ($items as $item) {
    $coverageReport->addItem(new Item($item));
}
if ($api->callSupplyCoverageReport($coverageReport)->isSuccess()) {
   echo('caricamento ok<br>');
}
$response = $api->callGetUnsentProductData();
$message = $response->getUnsentProductDataResult()->getMessage(); // get Message object

var_dump($message);
$api->callAcknowledgeMessage($message->getId());
var_dump($api);

?>
```
but i see this error:
Fatal error: Uncaught Error: Class 'RetailerFeedbackReport' not found 

i install all through composer.

**Comment by jecksolovyev** [comment]
Yup, you need to import these classes first, as Composer uses https://www.php-fig.org/psr/psr-4/ tactic to autoload classes

**Comment by Alias1975** [comment]
Hi Evgeniy sorry can help me?
i follow installation readme:

composer require jecksolovyev/brandbank-soap-api-client

<https://github.com/jecksolovyev/brandbank-soap-api-client#requirements>what
else do i have to do to make the class work?
can you send me an example pls?

Thanks a lot

Il giorno mar 10 set 2019 alle ore 12:06 Evgeniy Solovyev <
notifications@github.com> ha scritto:

**Comment by ugheddu** [comment]
Hi Evgeniy, I have the same problem of Alias1975. Can you post am example of how to import the class RetailerFeedbackReport ?

Thanks,
