### ISSUE TITLE
From ->getMessage() to xml file in php

### ISSUE THREAD

**Issue by Lechu85** [jecksolovyev/brandbank-soap-api-client#4]
Hello. 
I have problem. This code: 

`$message = $response->getUnsentProductDataResult()->getMessage(); `

return object. How to write this object to clean xml. 
I am using php. 
Can you help me?

**Comment by jecksolovyev** [comment]
Please see https://stackoverflow.com/questions/137021/php-object-as-xml-document or one of the similar solutions
